import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from "../Components/Navbar";
import Leaderboard from "../Components/Leaderboard";
import DishwasherGallery from "../Components/DishwasherGallery";
import {useSession} from "next-auth/client";

const Home: NextPage = () => {
    const [ session, loading ] = useSession();

    return (
        <div className={""}>
            <Head>
                <title>The best dishwasher</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navbar session={session} loading={loading}/>

            <main className={"flex flex-col h-full"}>
                <Leaderboard className={"pt-5"}/>
                <DishwasherGallery/>
            </main>

            <footer className={"w-screen sticky bottom-0 border-t-2 py-3 bg-white"}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                    className={"flex flex-row justify-center self-center"}
                >
                    <p className={"self-center"}> Check out my github, for the source code!</p>

                    <span className={"self-center flex ml-3"}>
            <Image className={"self-center"} src="/Octocat.png" alt="Github octocat Logo" width={72} height={64}/>
          </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
