import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from "../Components/Navbar";
import Leaderboard from "../Components/Leaderboard";
import DishwasherGallery from "../Components/DishwasherGallery";
import {useSession} from "next-auth/react";
import {useEffect, useState} from "react";


const Home: NextPage = () => {
    const { data: session, status } = useSession()
    const loading = status === "loading"
    const [reload, setReload] = useState(false);

    useEffect(() => {
        if(session){
            const response = fetch('/api/db', {
                method: "PUT",
                body: JSON.stringify({action: "?userLogin"})
            })
        }

    }, [session]) // Added [] as useEffect filter so it will be executed only once, when component is mounted

    return (
        <div className={""}>
            <Head>
                <title>The best dishwasher</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navbar session={session} loading={loading}/>

            <main className={"flex flex-col h-full "}>
                <Leaderboard className={"pt-5"} reload={reload} reloadDone={() => setReload(false)}/>
                <DishwasherGallery session={session} loading={loading} reloadLeaderboard={() => {setReload(true)}}/>
            </main>

            <footer className={" sticky bottom-0 border-t-2 py-3 bg-white"}>
                <a
                    href="https://github.com/Gulianrdgd/Counterexit"
                    target="_blank"
                    rel="noopener noreferrer"
                    className={"flex flex-row justify-center self-center"}
                >
                    <p className={"self-center"}> Check out my github, for the source code!</p>

                    <span className={"self-center flex ml-3"}>
                        <Image className={"self-center"} src="/Octocat.png" alt="Github octocat Logo" width={72}
                               height={64}/>
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
